version: "3"

services:
  strapibackend:
    image: dfgaviria/strapibackend
    build: backend
    container_name: strapibackend
    networks:
      - strapi-app-network
    ports:
       [1337:1337]

  restaurapp-frontend:
    image: dfgaviria/restaurant-app
    build: frontend
    container_name: restaurapp-frontend
    command: npm run dev
    depends_on:
      - strapibackend
    networks:
      - strapi-app-network
    ports:
      - "3000:3000"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapibackend:
    driver: local



