version: "3"

services:
  restaurapp-backend:
    image: dfgaviria/restaurapp-backend
    build: backend
    container_name: restaurapp-backend
    networks:
      - strapi-app-network
    ports:
       [1337:1337]

  restaurapp-frontend:
    image: dfgaviria/restauraap-frontend
    build: frontend
    container_name: restaurapp-frontend
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - restaurapp-backend
    networks:
      - strapi-app-network
    ports:
      - "3000:3000"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapibackend:
    driver: local



